server:
  port: 8764

spring:
  application:
    name: eureka-consumer-ribbon
  boot:
    admin:
      client:
        url: http://localhost:8084  #springboot-admin服务监控server地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
