server:
  port: 8766

spring:
  application:
    name: zuul
  zipkin: #zipkin 链路追踪
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: eureka-consumer-ribbon
    api-b:
      path: /api/b/**
      serviceId: eureka-consumer-feign

