#云端配置
spring:
  cloud:
    config:
      uri: http://localhost:8888
      name: eureka-consumer-feign
      label: master
      profile: dev
  zipkin: #zipkin 链路追踪
    base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8084  #springboot-admin服务监控server地址
# 本地配置
#server:
#  port: 8765
#
#spring:
#  application:
#    name: eureka-consumer-feign
#  cloud:
#    config:
#      uri: http://localhost:8888
#      name: config-client
#      label: master
#      profile: dev
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#feign:
#  hystrix:
#    enabled: true  #feign自带熔断器，开启服务熔断
