server:
  port: 8888   #默认8888

spring:
  application:
    name: config-server
  boot:
    admin:
      client:
        url: http://localhost:8084  #springboot-admin服务监控server地址
  zipkin: #zipkin 链路追踪
    base-url: http://localhost:9411
  cloud:
    config:
      label: master   #配置仓库分支
      server:
        git:
          uri: https://github.com/yeshang5/springcloud-config-server.git   #仓库地址
          username: 646066936@qq.com               #访问Git仓库的账号
          password: lovebh19951127!!              #访问Git仓库的密码
          search-paths: respo   #配置仓库路径(存放配置文件的目录)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8760/eureka/
  instance:
    prefer-ip-address: true   #使用ip地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}   #向注册中心注册服务id
    lease-renewal-interval-in-seconds: 5  #向注册中心注册服务id
    lease-expiration-duration-in-seconds: 10  #续约到期的时间

#暴露健康检查信息,供spingboot-Admin服务监控使用
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

