server:
  port: 8888   #默认8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master   #配置仓库分支
      server:
        git:
          uri: https://github.com/yeshang5/springcloud-config-server.git   #仓库地址
          username:               #访问Git仓库的账号
          password:               #访问Git仓库的密码
          search-paths: respo   #配置仓库路径(存放配置文件的目录)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

